# Site settings
title: Ahao
header-img: "img/autumn2.jpg"
description: "人生在勤，不索何获？"  
baseurl: ""
url: "http://first12.github.io"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "Ahao"
  email: wh1995@gmail.com
  bio: "人生在勤，不索何获？"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: 
twitter_username:   
github_username: first12  
facebook_username:   
weibo_username:   
zhihu_username:   

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

gems: [jekyll-paginate]
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ahao"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : Ahao
  disqus :
      short_name : Ahao

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
